In [ ]:
fruits = ["apple","APPLE","Apple"]
new_fruits = []
for fruit in fruits:
    new_fruits.append(fruit.lower())
print(new_fruits)

['apple', 'apple', 'apple']

In [ ]:
fruits = ["apple","APPLE","Apple"]
new_fruits = [fruit.lower() for fruit in fruits]
print(new_fruits)

['apple', 'apple', 'apple']

In [ ]:
numbers = [85, -10, 90, -5, 75]

positive_list = [num for num in numbers if num > 0]

print(positive_list)

[85, 90, 75]

In [ ]:
numbers = [85, -10, 90, -5, 75]

positive_list = []

for num in numbers:
    if num > 0:
        positive_list.append(num)

print(positive_list)

[85, 90, 75]

In [ ]:
import pandas as pd

data = pd.read_csv("employees.csv")
display(data)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
import pandas as pd

data = pd.read_csv("employees.csv")
data.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [ ]:
import pandas as pd

data = pd.read_csv("employees.csv")
data.head(10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development

In [ ]:
import pandas as pd

data = pd.read_csv("employees.csv")
data.tail(10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
990,Robin,Female,7/24/1987,1:35 PM,100765,10.982,True,Client Services
991,Rose,Female,8/25/2002,5:12 AM,134505,11.051,True,Marketing
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
993,Tina,Female,5/15/1997,3:53 PM,56450,19.040,True,Engineering
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
import pandas as pd

df = pd.read_csv("employees.csv")
df.isnull()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,True,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [ ]:
import pandas as pd

df = pd.read_csv("employees.csv")
df.isnull().sum()

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

In [ ]:
print(df['First Name'].isnull().sum())

67

In [ ]:
df['First Name'].fillna("Unknown",inplace=True)

In [ ]:
print(df['First Name'].isnull().sum())

0

In [ ]:
df['First Name'].head(30)

0      Douglas
1       Thomas
2        Maria
3        Jerry
4        Larry
5       Dennis
6         Ruby
7      Unknown
8       Angela
9      Frances
10      Louise
11       Julie
12     Brandon
13        Gary
14    Kimberly
15     Lillian
16      Jeremy
17       Shawn
18       Diana
19       Donna
20        Lois
21     Matthew
22      Joshua
23     Unknown
24        John
25     Unknown
26       Craig
27       Scott
28       Terry
29    Benjamin
Name: First Name, dtype: object

In [ ]:
df['Senior Management'].fillna("Unknown",inplace=True)

In [ ]:
print(df['Senior Management'].isnull().sum())

0

In [ ]:
df['Team'].fillna("Unknown",inplace=True)

In [ ]:
print(df['Team'].isnull().sum())

0

In [ ]:
df['Gender'].fillna("Unknown",inplace=True)

In [ ]:
print(df['Team'].isnull().sum())

0

In [ ]:
print(df.dtypes)

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

In [ ]:
df.describe()

              Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000

In [ ]:
print(df["Gender"].unique())

['Male' 'Female' 'Unknown']

In [ ]:
df = pd.read_csv("Indian_State_Statistics_Dataset.csv")

In [ ]:
df

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
0,Andhra Pradesh,52221000,Telugu,28.9,1.4,4.8,Yuvajana Sramika Rythu Congress Party (YSRCP),25
1,Arunachal Pradesh,1575000,English,35.5,1.6,4.2,Bharatiya Janata Party (BJP),2
2,Assam,34293000,Assamese,34.2,2.3,4.0,Bharatiya Janata Party (BJP),14
3,Bihar,124799000,Hindi,35.7,0.6,3.4,Rashtriya Janata Dal (RJD),40
4,Chhattisgarh,28724000,Chhattisgarhi,33.7,1.2,3.8,Indian National Congress (INC),11
5,Goa,1540000,Konkani,31.4,1.5,7.8,Bharatiya Janata Party (BJP),2
6,Gujarat,63907000,Gujarati,34.8,0.8,0.9,Bharatiya Janata Party (BJP),26
7,Haryana,28238000,Hindi,32.2,0.7,2.1,Bharatiya Janata Party (BJP),10
8,Himachal Pradesh,7300000,Hindi,31.4,0.9,2.6,Bharatiya Janata Party (BJP),4
9,Jharkhand,37403000,Hindi,35.2,1.1,3.2,Bharatiya Janata Party (BJP),14
10,Karnataka,67557000,Kannada,32.9,1.2,2.3,Bharatiya Janata Party (BJP),28
11,Kerala,35657000,Malayalam,26.5,0.4,9.0,Communist Party of India (Marxist) (CPI(M)),20
12,Madhya Pradesh,82232000,Hindi,33.4,1.0,4.3,Bharatiya Janata Party (BJP),29
13,Maharashtra,123140000,Marathi,31.9,0.9,3.9,Bharatiya Janata Party (BJP),48
14,Manipur,3400000,Meiteilon,35.1,0.7,3.4,Bharatiya Janata Party (BJP),2
15,Meghalaya,3364000,English,31.7,0.8,3.0,Indian National Congress (INC),2
16,Mizoram,1192000,Mizo,33.1,0.6,2.7,Mizo National Front (MNF),1
17,Nagaland,2244000,English,35.2,0.7,1.4,Naga People's Front (NPF),1
18,Odisha,46356000,Odia,33.4,0.8,3.6,Biju Janata Dal (BJD),21
19,Punjab,30184000,Punjabi,29.7,0.6,3.8,Indian National Congress (INC),13
20,Rajasthan,81067000,Hindi,33.6,0.9,1.5,Bharatiya Janata Party (BJP),25
21,Sikkim,690000,Sikkimese,31.9,0.5,3.6,Sikkim Krantikari Morcha (SKM),1
22,Tamil Nadu,75695000,Tamil,29.1,0.8,2.7,Dravida Munnetra Kazhagam (DMK),39
23,Telangana,37220000,Telugu,31.9,0.7,6.0,Telangana Rashtra Samithi (TRS),17
24,Tripura,4160000,Bengali,31.4,0.8,4.3,Bharatiya Janata Party (BJP),2
25,Uttar Pradesh,224979000,Hindi,34.8,0.6,3.7,Bharatiya Janata Party (BJP),80
26,Uttarakhand,11251000,Hindi,33.2,0.7,1.1,Bharatiya Janata Party (BJP),5
27,West Bengal,99609000,Bengali,28.1,0.5,4.6,All India Trinamool Congress (AITC),42

In [ ]:
df[['State']]

                State
0      Andhra Pradesh
1   Arunachal Pradesh
2               Assam
3               Bihar
4        Chhattisgarh
5                 Goa
6             Gujarat
7             Haryana
8    Himachal Pradesh
9           Jharkhand
10          Karnataka
11             Kerala
12     Madhya Pradesh
13        Maharashtra
14            Manipur
15          Meghalaya
16            Mizoram
17           Nagaland
18             Odisha
19             Punjab
20          Rajasthan
21             Sikkim
22         Tamil Nadu
23          Telangana
24            Tripura
25      Uttar Pradesh
26        Uttarakhand
27        West Bengal

In [ ]:
df[['Language']]

         Language
0          Telugu
1         English
2        Assamese
3           Hindi
4   Chhattisgarhi
5         Konkani
6        Gujarati
7           Hindi
8           Hindi
9           Hindi
10        Kannada
11      Malayalam
12          Hindi
13        Marathi
14      Meiteilon
15        English
16           Mizo
17        English
18           Odia
19        Punjabi
20          Hindi
21      Sikkimese
22          Tamil
23         Telugu
24        Bengali
25          Hindi
26          Hindi
27        Bengali

In [ ]:
df[['State','Language']]

                State       Language
0      Andhra Pradesh         Telugu
1   Arunachal Pradesh        English
2               Assam       Assamese
3               Bihar          Hindi
4        Chhattisgarh  Chhattisgarhi
5                 Goa        Konkani
6             Gujarat       Gujarati
7             Haryana          Hindi
8    Himachal Pradesh          Hindi
9           Jharkhand          Hindi
10          Karnataka        Kannada
11             Kerala      Malayalam
12     Madhya Pradesh          Hindi
13        Maharashtra        Marathi
14            Manipur      Meiteilon
15          Meghalaya        English
16            Mizoram           Mizo
17           Nagaland        English
18             Odisha           Odia
19             Punjab        Punjabi
20          Rajasthan          Hindi
21             Sikkim      Sikkimese
22         Tamil Nadu          Tamil
23          Telangana         Telugu
24            Tripura        Bengali
25      Uttar Pradesh          Hindi
26        Uttarakhand          Hindi
27        West Bengal        Bengali

In [ ]:
dfc=df.copy()

In [ ]:
dfc['State']=='Bihar'

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
Name: State, dtype: bool

In [ ]:
bihar_data=dfc.loc[df['State']=='Bihar']

In [ ]:
bihar_data

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
3,Bihar,124799000,Hindi,35.7,0.6,3.4,Rashtriya Janata Dal (RJD),40

In [ ]:
dfc['State']=='Goa'

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
Name: State, dtype: bool

In [ ]:
goa_data=dfc.loc[dfc['State']=='Goa']
goa_data

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
5,Goa,1540000,Konkani,31.4,1.5,7.8,Bharatiya Janata Party (BJP),2

In [ ]:
dfc[dfc['State'].str.startswith('K')]

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
10,Karnataka,67557000,Kannada,32.9,1.2,2.3,Bharatiya Janata Party (BJP),28
11,Kerala,35657000,Malayalam,26.5,0.4,9.0,Communist Party of India (Marxist) (CPI(M)),20

In [ ]:
dfc[dfc['State'].str.startswith('M')]

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
12,Madhya Pradesh,82232000,Hindi,33.4,1.0,4.3,Bharatiya Janata Party (BJP),29
13,Maharashtra,123140000,Marathi,31.9,0.9,3.9,Bharatiya Janata Party (BJP),48
14,Manipur,3400000,Meiteilon,35.1,0.7,3.4,Bharatiya Janata Party (BJP),2
15,Meghalaya,3364000,English,31.7,0.8,3.0,Indian National Congress (INC),2
16,Mizoram,1192000,Mizo,33.1,0.6,2.7,Mizo National Front (MNF),1

In [ ]:
max(dfc['Population'])

224979000

In [ ]:
state_with_highest_population=dfc.loc[dfc['Population'].idxmax()]
state_with_highest_population

State                             Uttar Pradesh
Population                            224979000
Language                                  Hindi
Youth %                                    34.8
Divorce rate                                0.6
Unemployment                                3.7
Ruling Party       Bharatiya Janata Party (BJP)
Lok Sabha Seats                              80
Name: 25, dtype: object

In [ ]:
state_with_highest_youth=dfc.loc[dfc['Youth %'].idxmax()]
state_with_highest_youth

State                                   Bihar
Population                          124799000
Language                                Hindi
Youth %                                  35.7
Divorce rate                              0.6
Unemployment                              3.4
Ruling Party       Rashtriya Janata Dal (RJD)
Lok Sabha Seats                            40
Name: 3, dtype: object

In [ ]:
import pandas as pd

data ={
    'Names':['Krish','Hari','Alex',None,"Ajay","Krishna"],
    'Age':[29,None,25,29,None,31]
}

df=pd.DataFrame(data)
df

     Names   Age
0    Krish  29.0
1     Hari   NaN
2     Alex  25.0
3     None  29.0
4     Ajay   NaN
5  Krishna  31.0

In [ ]:
print(df.loc[1,'Names'])

Hari

In [ ]:
dfc[dfc['State'].str.startswith('K')]

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
10,Karnataka,67557000,Kannada,32.9,1.2,2.3,Bharatiya Janata Party (BJP),28
11,Kerala,35657000,Malayalam,26.5,0.4,9.0,Communist Party of India (Marxist) (CPI(M)),20

In [ ]:
bjp_ruled_state=dfc[dfc['Ruling Party'] == 'Bharatiya Janata Party (BJP)']
bjp_ruled_state

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
1,Arunachal Pradesh,1575000,English,35.5,1.6,4.2,Bharatiya Janata Party (BJP),2
2,Assam,34293000,Assamese,34.2,2.3,4.0,Bharatiya Janata Party (BJP),14
5,Goa,1540000,Konkani,31.4,1.5,7.8,Bharatiya Janata Party (BJP),2
6,Gujarat,63907000,Gujarati,34.8,0.8,0.9,Bharatiya Janata Party (BJP),26
7,Haryana,28238000,Hindi,32.2,0.7,2.1,Bharatiya Janata Party (BJP),10
8,Himachal Pradesh,7300000,Hindi,31.4,0.9,2.6,Bharatiya Janata Party (BJP),4
9,Jharkhand,37403000,Hindi,35.2,1.1,3.2,Bharatiya Janata Party (BJP),14
10,Karnataka,67557000,Kannada,32.9,1.2,2.3,Bharatiya Janata Party (BJP),28
12,Madhya Pradesh,82232000,Hindi,33.4,1.0,4.3,Bharatiya Janata Party (BJP),29
13,Maharashtra,123140000,Marathi,31.9,0.9,3.9,Bharatiya Janata Party (BJP),48
14,Manipur,3400000,Meiteilon,35.1,0.7,3.4,Bharatiya Janata Party (BJP),2
20,Rajasthan,81067000,Hindi,33.6,0.9,1.5,Bharatiya Janata Party (BJP),25
24,Tripura,4160000,Bengali,31.4,0.8,4.3,Bharatiya Janata Party (BJP),2
25,Uttar Pradesh,224979000,Hindi,34.8,0.6,3.7,Bharatiya Janata Party (BJP),80
26,Uttarakhand,11251000,Hindi,33.2,0.7,1.1,Bharatiya Janata Party (BJP),5

In [ ]:
state_with_highest_lok_sabha=dfc.loc[dfc['Lok Sabha Seats'].idxmax()]
state_with_highest_lok_sabha['State']

'Uttar Pradesh'

In [ ]:
max(dfc['Lok Sabha Seats'])

80

In [ ]:
total_bjp_ruled_state=len(bjp_ruled_state)
total_bjp_ruled_state

15

In [ ]:
total_number_of_state=len(dfc['State'])
total_number_of_state

28

In [ ]:
left_state=total_number_of_state-total_bjp_ruled_state
left_state

13

In [ ]:
congress_ruled_state=dfc[dfc['Ruling Party'] == 'Indian National Congress (INC)']
congress_ruled_state

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
4,Chhattisgarh,28724000,Chhattisgarhi,33.7,1.2,3.8,Indian National Congress (INC),11
15,Meghalaya,3364000,English,31.7,0.8,3.0,Indian National Congress (INC),2
19,Punjab,30184000,Punjabi,29.7,0.6,3.8,Indian National Congress (INC),13

In [ ]:
total_ruled_by_congress=len(congress_ruled_state)
total_ruled_by_congress

3

In [ ]:
dfc[dfc['Language']=='Hindi']

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
3,Bihar,124799000,Hindi,35.7,0.6,3.4,Rashtriya Janata Dal (RJD),40
7,Haryana,28238000,Hindi,32.2,0.7,2.1,Bharatiya Janata Party (BJP),10
8,Himachal Pradesh,7300000,Hindi,31.4,0.9,2.6,Bharatiya Janata Party (BJP),4
9,Jharkhand,37403000,Hindi,35.2,1.1,3.2,Bharatiya Janata Party (BJP),14
12,Madhya Pradesh,82232000,Hindi,33.4,1.0,4.3,Bharatiya Janata Party (BJP),29
20,Rajasthan,81067000,Hindi,33.6,0.9,1.5,Bharatiya Janata Party (BJP),25
25,Uttar Pradesh,224979000,Hindi,34.8,0.6,3.7,Bharatiya Janata Party (BJP),80
26,Uttarakhand,11251000,Hindi,33.2,0.7,1.1,Bharatiya Janata Party (BJP),5

In [ ]:
dfc.loc[dfc['State']=='Bihar','Language']='Bhojpuri'
dfc

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
0,Andhra Pradesh,52221000,Telugu,28.9,1.4,4.8,Yuvajana Sramika Rythu Congress Party (YSRCP),25
1,Arunachal Pradesh,1575000,English,35.5,1.6,4.2,Bharatiya Janata Party (BJP),2
2,Assam,34293000,Assamese,34.2,2.3,4.0,Bharatiya Janata Party (BJP),14
3,Bihar,124799000,Bhojpuri,35.7,0.6,3.4,Rashtriya Janata Dal (RJD),40
4,Chhattisgarh,28724000,Chhattisgarhi,33.7,1.2,3.8,Indian National Congress (INC),11
5,Goa,1540000,Konkani,31.4,1.5,7.8,Bharatiya Janata Party (BJP),2
6,Gujarat,63907000,Gujarati,34.8,0.8,0.9,Bharatiya Janata Party (BJP),26
7,Haryana,28238000,Hindi,32.2,0.7,2.1,Bharatiya Janata Party (BJP),10
8,Himachal Pradesh,7300000,Hindi,31.4,0.9,2.6,Bharatiya Janata Party (BJP),4
9,Jharkhand,37403000,Hindi,35.2,1.1,3.2,Bharatiya Janata Party (BJP),14
10,Karnataka,67557000,Kannada,32.9,1.2,2.3,Bharatiya Janata Party (BJP),28
11,Kerala,35657000,Malayalam,26.5,0.4,9.0,Communist Party of India (Marxist) (CPI(M)),20
12,Madhya Pradesh,82232000,Hindi,33.4,1.0,4.3,Bharatiya Janata Party (BJP),29
13,Maharashtra,123140000,Marathi,31.9,0.9,3.9,Bharatiya Janata Party (BJP),48
14,Manipur,3400000,Meiteilon,35.1,0.7,3.4,Bharatiya Janata Party (BJP),2
15,Meghalaya,3364000,English,31.7,0.8,3.0,Indian National Congress (INC),2
16,Mizoram,1192000,Mizo,33.1,0.6,2.7,Mizo National Front (MNF),1
17,Nagaland,2244000,English,35.2,0.7,1.4,Naga People's Front (NPF),1
18,Odisha,46356000,Odia,33.4,0.8,3.6,Biju Janata Dal (BJD),21
19,Punjab,30184000,Punjabi,29.7,0.6,3.8,Indian National Congress (INC),13
20,Rajasthan,81067000,Hindi,33.6,0.9,1.5,Bharatiya Janata Party (BJP),25
21,Sikkim,690000,Sikkimese,31.9,0.5,3.6,Sikkim Krantikari Morcha (SKM),1
22,Tamil Nadu,75695000,Tamil,29.1,0.8,2.7,Dravida Munnetra Kazhagam (DMK),39
23,Telangana,37220000,Telugu,31.9,0.7,6.0,Telangana Rashtra Samithi (TRS),17
24,Tripura,4160000,Bengali,31.4,0.8,4.3,Bharatiya Janata Party (BJP),2
25,Uttar Pradesh,224979000,Hindi,34.8,0.6,3.7,Bharatiya Janata Party (BJP),80
26,Uttarakhand,11251000,Hindi,33.2,0.7,1.1,Bharatiya Janata Party (BJP),5
27,West Bengal,99609000,Bengali,28.1,0.5,4.6,All India Trinamool Congress (AITC),42

In [ ]:
dfc[dfc['Youth %']>30]

,State,Population,Language,Youth %,Divorce rate,Unemployment,Ruling Party,Lok Sabha Seats
1,Arunachal Pradesh,1575000,English,35.5,1.6,4.2,Bharatiya Janata Party (BJP),2
2,Assam,34293000,Assamese,34.2,2.3,4.0,Bharatiya Janata Party (BJP),14
3,Bihar,124799000,Bhojpuri,35.7,0.6,3.4,Rashtriya Janata Dal (RJD),40
4,Chhattisgarh,28724000,Chhattisgarhi,33.7,1.2,3.8,Indian National Congress (INC),11
5,Goa,1540000,Konkani,31.4,1.5,7.8,Bharatiya Janata Party (BJP),2
6,Gujarat,63907000,Gujarati,34.8,0.8,0.9,Bharatiya Janata Party (BJP),26
7,Haryana,28238000,Hindi,32.2,0.7,2.1,Bharatiya Janata Party (BJP),10
8,Himachal Pradesh,7300000,Hindi,31.4,0.9,2.6,Bharatiya Janata Party (BJP),4
9,Jharkhand,37403000,Hindi,35.2,1.1,3.2,Bharatiya Janata Party (BJP),14
10,Karnataka,67557000,Kannada,32.9,1.2,2.3,Bharatiya Janata Party (BJP),28
12,Madhya Pradesh,82232000,Hindi,33.4,1.0,4.3,Bharatiya Janata Party (BJP),29
13,Maharashtra,123140000,Marathi,31.9,0.9,3.9,Bharatiya Janata Party (BJP),48
14,Manipur,3400000,Meiteilon,35.1,0.7,3.4,Bharatiya Janata Party (BJP),2
15,Meghalaya,3364000,English,31.7,0.8,3.0,Indian National Congress (INC),2
16,Mizoram,1192000,Mizo,33.1,0.6,2.7,Mizo National Front (MNF),1
17,Nagaland,2244000,English,35.2,0.7,1.4,Naga People's Front (NPF),1
18,Odisha,46356000,Odia,33.4,0.8,3.6,Biju Janata Dal (BJD),21
20,Rajasthan,81067000,Hindi,33.6,0.9,1.5,Bharatiya Janata Party (BJP),25
21,Sikkim,690000,Sikkimese,31.9,0.5,3.6,Sikkim Krantikari Morcha (SKM),1
23,Telangana,37220000,Telugu,31.9,0.7,6.0,Telangana Rashtra Samithi (TRS),17
24,Tripura,4160000,Bengali,31.4,0.8,4.3,Bharatiya Janata Party (BJP),2
25,Uttar Pradesh,224979000,Hindi,34.8,0.6,3.7,Bharatiya Janata Party (BJP),80
26,Uttarakhand,11251000,Hindi,33.2,0.7,1.1,Bharatiya Janata Party (BJP),5