In [ ]:
import pandas as pd

df = pd.read_csv("employees.csv")

df.columns = df.columns.str.title()

In [ ]:
# 1. How to display only 5 rows?
df.head()

,Employee_Id,First_Name,Last_Name,Email,Phone_Number,Hire_Date,Job_Id,Salary,Commission_Pct,Manager_Id,Department_Id
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [ ]:
# 2. How to display only 10 rows?
df.head(10)

,Employee_Id,First_Name,Last_Name,Email,Phone_Number,Hire_Date,Job_Id,Salary,Commission_Pct,Manager_Id,Department_Id
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90

In [ ]:
# 3. How to fetch all column names?
print(df.columns)

Index(['Employee_Id', 'First_Name', 'Last_Name', 'Email', 'Phone_Number',
       'Hire_Date', 'Job_Id', 'Salary', 'Commission_Pct', 'Manager_Id',
       'Department_Id'],
      dtype='object')

In [ ]:
# 4. Email column data in lowercase
df["Email"] = df["Email"].str.lower()

In [ ]:
# 5. Make all column names first letter uppercase rest lowercase
df.columns = df.columns.str.title()

In [ ]:
# 6. Why lower case not change original data?
df["Email"].str.lower()

0     doconnel
1       dgrant
2      jwhalen
3     mhartste
4         pfay
5      smavris
6        hbaer
7     shiggins
8       wgietz
9        sking
10    nkochhar
11     ldehaan
12     ahunold
13      bernst
14     daustin
15    vpatabal
16    dlorentz
17    ngreenbe
18     dfaviet
19       jchen
20    isciarra
21     jmurman
22       lpopp
23    drapheal
24       akhoo
25      sbaida
26     stobias
27     ghimuro
28    kcolmena
29      jpatel
Name: Email, dtype: object

In [ ]:
# 7. Need all first name start with D
df[df["First_Name"].str.startswith("D")]

,Employee_Id,First_Name,Last_Name,Email,Phone_Number,Hire_Date,Job_Id,Salary,Commission_Pct,Manager_Id,Department_Id
0,198,Donald,OConnell,doconnel,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,dgrant,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
14,105,David,Austin,daustin,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,dlorentz,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
18,109,Daniel,Faviet,dfaviet,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
23,114,Den,Raphaely,drapheal,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30

In [ ]:
# 8. Combine first name & last name and make Full_Name column
df["Full_Name"] = df["First_Name"] + " " + df["Last_Name"]

In [ ]:
# 9. Delete data of Donald
df = df[df["First_Name"] != "Donald"]

In [ ]:
# 10. Change position of column
col = df.pop("First_Name")
df.insert(0, "First_Name", col)

In [ ]:
# 11. Print all people salary greater than 10000
df[df["Salary"] > 10000]

# Count all people salary greater than 10000
df[df["Salary"] > 10000].shape[0]

7

In [ ]:
# 12. Need all people hired in 2005
df[df["Hire_Date"].str.contains("05")]

,First_Name,Employee_Id,Last_Name,Email,Phone_Number,Hire_Date,Job_Id,Salary,Commission_Pct,Manager_Id,Department_Id,Full_Name
4,Pat,202,Fay,pfay,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20,Pat Fay
10,Neena,101,Kochhar,nkochhar,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90,Neena Kochhar
14,David,105,Austin,daustin,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60,David Austin
15,Valli,106,Pataballa,vpatabal,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60,Valli Pataballa
19,John,110,Chen,jchen,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100,John Chen
20,Ismael,111,Sciarra,isciarra,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100,Ismael Sciarra
25,Shelli,116,Baida,sbaida,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30,Shelli Baida
26,Sigal,117,Tobias,stobias,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30,Sigal Tobias

In [ ]:
# 13. Need all people hired in Aug
df[df["Hire_Date"].str.contains("AUG")]

,First_Name,Employee_Id,Last_Name,Email,Phone_Number,Hire_Date,Job_Id,Salary,Commission_Pct,Manager_Id,Department_Id,Full_Name
4,Pat,202,Fay,pfay,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20,Pat Fay
17,Nancy,108,Greenberg,ngreenbe,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100,Nancy Greenberg
18,Daniel,109,Faviet,dfaviet,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100,Daniel Faviet
28,Karen,119,Colmenares,kcolmena,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30,Karen Colmenares