In [ ]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import numpy

In [ ]:
arr1 = numpy.array([1,2,3,4])
arr2 = numpy.array([1,2,3,4])
print(arr1 + arr2)

[2 4 6 8]

In [ ]:
arr1 = numpy.array([1,2,3,4])

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1)
print(arr2)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]

In [ ]:
res = numpy.arange(0,10,2)
print(res)

[0 2 4 6 8]

In [ ]:
res = numpy.linspace(0,10)
print(res)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]

In [ ]:
res1 = np.zeros((2,3))     # 2x3 matrix of 0s
res2 = np.ones((2,3))      # 2x3 matrix of 1s
res3 = np.arange(0,10,2)   # [0 2 4 6 8]
res4 = np.linspace(1,5,5)  # [1. 2. 3. 4. 5.]
res5 = np.eye(3)           # 3x3 Identity matrix
print(res1)
print(res2)
print(res3)
print(res4)
print(res5)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[1. 2. 3. 4. 5.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64

In [ ]:
arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[-1])
print(arr[1:4])

10
50
[20 30 40]

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd

data = [10, 20, 30, 40]
s = pd.Series(data, index=['a','b','c','d'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
import pandas as pd
data = {
    "Name": ["Amit", "Ravi", "Priya"],
    "Age": [25, 30, 22],
    "City": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
display(df)

    Name  Age    City
0   Amit   25   Delhi
1   Ravi   30  Mumbai
2  Priya   22    Pune

In [ ]:

print(df.head(1))       # First 5 rows
print(df.tail(2))      # Last 2 rows
print(df.shape)        # (rows, columns)
print(df.columns)      # Column names
print(df.info())       # Summary
print(df.describe())   # Stats summary

   Name  Age   City
0  Amit   25  Delhi
    Name  Age    City
1   Ravi   30  Mumbai
2  Priya   22    Pune
(3, 3)
Index(['Name', 'Age', 'City'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
             Age
count   3.000000
mean   25.666667
std     4.041452
min    22.000000
25%    23.500000
50%    25.000000
75%    27.500000
max    30.000000

In [ ]:
print(df["Name"])        # Select column
print(df[["Name","Age"]])# Multiple columns
print(df.iloc[0])        # Row by index
print(df.loc[1])         # Row by label

0     Amit
1     Ravi
2    Priya
Name: Name, dtype: object
    Name  Age
0   Amit   25
1   Ravi   30
2  Priya   22
Name     Amit
Age        25
City    Delhi
Name: 0, dtype: object
Name      Ravi
Age         30
City    Mumbai
Name: 1, dtype: object

In [ ]:
print(df[df["Age"] > 23])    # Filter rows

   Name  Age    City
0  Amit   25   Delhi
1  Ravi   30  Mumbai

In [ ]:
import pandas as pd
data = {
"Name": ["Apoorv", "Ravi", "Sneha", "Kiran", "Anjali"],
"marks": [98, 62, 89, 93, 81],
}
df = pd.DataFrame(data)
display(df)
display(df[df["marks"]>80])
display(df["marks"].max())

     Name  marks
0  Apoorv     98
1    Ravi     62
2   Sneha     89
3   Kiran     93
4  Anjali     81

     Name  marks
0  Apoorv     98
2   Sneha     89
3   Kiran     93
4  Anjali     81

98

In [ ]:
sorted_df = df.sort_values(by="marks", ascending=True)
display(sorted_df)

     Name  marks
1    Ravi     62
4  Anjali     81
2   Sneha     89
3   Kiran     93
0  Apoorv     98

In [ ]:
df["Age"] = [15, 16, 14, 17, 15]        # Example ages
df["Age_plus_10"] = df["Age"] + 10

display(df)

     Name  marks  Age  Age_plus_10
0  Apoorv     98   15           25
1    Ravi     62   16           26
2   Sneha     89   14           24
3   Kiran     93   17           27
4  Anjali     81   15           25

In [ ]:
df["marks_plus_10"] = df["marks"] + 10

display(df)

     Name  marks  Age  Age_plus_10  marks_plus_10
0  Apoorv     98   15           25            108
1    Ravi     62   16           26             72
2   Sneha     89   14           24             99
3   Kiran     93   17           27            103
4  Anjali     81   15           25             91

In [ ]:
df["City"] = ["Mumbai", "Thane", "Pune", "Navi Mumbai", "Mumbai"]

display(df[df['City']=="Mumbai"])

     Name  marks  Age  Age_plus_10  marks_plus_10    City
0  Apoorv     98   15           25            108  Mumbai
4  Anjali     81   15           25             91  Mumbai